#Problem 2: Even Fibonacci numbers
#
#Source: https://projecteuler.net/problem=2
#
#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
#
#Daniel Backx
#

sum = 0
x = 1
x1 = 0
x2 = 1
num = 1


userInput = input('\nProblem 2: Even Fibonacci numbers\n\n\tFind the sum of the even-valued terms by considering the terms in the Fibonacci sequence whose values do not exceed: ')

max = int(userInput)

while x2<max:
	x+=1


	num = x1+x2
	x1 = x2
	x2 = num

	if x%3==0:
		sum += num

print('\nThe sum of all the even-valued terms not exeeding', max, 'is:', sum, '\n\n')
